// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlbgvrahyuwnmbkvjugk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsYmd2cmFoeXV3bm1ia3ZqdWdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwNDQ5NzksImV4cCI6MjA1MjYyMDk3OX0.k2_xVDVUr9T8CVD_MzOm-Z4nl49pfQl-tDyouT8LwBk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);